name: ci

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.3", "8.4"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: xdebug

      - name: cache composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-

      - name: install dependencies
        run: composer install --prefer-dist --no-progress

      - name: run tests
        run: vendor/bin/pest

  static-analysis:
    name: static analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite

      - name: cache composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-8.4-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-8.4-composer-

      - name: install dependencies
        run: composer install --prefer-dist --no-progress

      - name: run static analysis
        run: composer stan

  php-code-style:
    name: php code style
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, xml, ctype, iconv, intl

      - name: cache composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-8.4-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-8.4-composer-

      - name: install dependencies
        run: composer install --prefer-dist --no-progress

      - name: check code style
        run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix --dry-run --diff

  js-lint-and-format:
    name: js lint and format
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: install pnpm
        uses: pnpm/action-setup@v3

      - name: install node dependencies
        run: pnpm install --frozen-lockfile

      - name: run eslint
        run: pnpm run lint

      - name: check prettier formatting
        run: pnpm exec prettier --check "src/**/*.{js,vue}"
